export const GET_CATEGORIES_LEVEL_REQUEST = "GET_CATEGORIES_LEVEL_REQUEST"
export const GET_CATEGORIES_LEVEL_SUCCESS = "GET_CATEGORIES_LEVEL_SUCCESS"
export const GET_CATEGORIES_LEVEL_FAILURE = "GET_CATEGORIES_LEVEL_FAILURE"

export const GET_CATEGORIES_LEVEL2_REQUEST = "GET_CATEGORIES_LEVEL2_REQUEST"
export const GET_CATEGORIES_LEVEL2_SUCCESS = "GET_CATEGORIES_LEVEL2_SUCCESS"
export const GET_CATEGORIES_LEVEL2_FAILURE = "GET_CATEGORIES_LEVEL2_FAILURE"




